In [17]:
import pandas as pd
import numpy as np

In [18]:
ta = pd.read_csv(r"C:\Users\HARSH\Desktop\python dataset\Trip_advisor_review.csv")

In [19]:
ta.shape

(20491, 2)

In [20]:
ta.head()

Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [21]:
ta.isnull().sum()[ta.isnull().sum()>0]

Series([], dtype: int64)

In [22]:
ta = ta.rename(columns = ({"Rating" : "Y" , "Review" : "X"}))

In [23]:
ta.head()

X  Y
0  nice hotel expensive parking got good deal sta...  4
1  ok nothing special charge diamond member hilto...  2
2  nice rooms not 4* experience hotel monaco seat...  3
3  unique, great stay, wonderful time hotel monac...  5
4  great stay great stay, went seahawk game aweso...  5

In [24]:
ta.Y.value_counts()

5    9054
4    6039
3    2184
2    1793
1    1421
Name: Y, dtype: int64

In [25]:
ta.X = ta.X.str.lower() # Mandtory
ta

X  Y
0      nice hotel expensive parking got good deal sta...  4
1      ok nothing special charge diamond member hilto...  2
2      nice rooms not 4* experience hotel monaco seat...  3
3      unique, great stay, wonderful time hotel monac...  5
4      great stay great stay, went seahawk game aweso...  5
...                                                  ... ..
20486  best kept secret 3rd time staying charm, not 5...  5
20487  great location price view hotel great quick pl...  4
20488  ok just looks nice modern outside, desk staff ...  2
20489  hotel theft ruined vacation hotel opened sept ...  1
20490  people talking, ca n't believe excellent ratin...  2

[20491 rows x 2 columns]

In [26]:
import nltk # nltk - natural language toolkit

In [27]:
from nltk.corpus import stopwords

In [28]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [72]:
ta.Y.value_counts()

5    9054
4    6039
3    2184
2    1793
1    1421
Name: Y, dtype: int64

In [73]:
# ta.Y.replace({2:1,3:2,4:3,5:3},inplace=True)
# ta.Y.value_counts()

3    15093
1     3214
2     2184
Name: Y, dtype: int64

In [117]:
ta.Y.replace({2:1,3:2,4:2,5:2},inplace=True)
ta.Y.value_counts()

2    15093
1     5398
Name: Y, dtype: int64

In [118]:
l1 = stopwords.words("english")

In [119]:
def text_process(mess):            ### creating a function

    """                                                        ## a docstring

    1. remove the punctuation

    2. remove the stopwords

    3. return the list of clean textwords

    

    """

    nopunc = [char for char in mess if char not in string.punctuation]

    nopunc = "".join(nopunc)

    

    return [ word for word in nopunc.split() if word not in l1]

In [120]:
# ta["X"].apply(text_process)

In [121]:
from sklearn.feature_extraction.text import CountVectorizer

In [122]:
bow_transformer = CountVectorizer(analyzer = text_process).fit(ta["X"])

In [123]:
bow_transformer.vocabulary_

{'nice': 49206,
 'hotel': 36909,
 'expensive': 28378,
 'parking': 53208,
 'got': 33582,
 'good': 33347,
 'deal': 21915,
 'stay': 68556,
 'anniversary': 6999,
 'arrived': 8200,
 'late': 42141,
 'evening': 27588,
 'took': 73466,
 'advice': 5264,
 'previous': 56545,
 'reviews': 61027,
 'valet': 76980,
 'check': 16606,
 'quick': 57945,
 'easy': 25627,
 'little': 43220,
 'disappointed': 23592,
 'nonexistent': 49873,
 'view': 77537,
 'room': 61740,
 'clean': 17592,
 'size': 65815,
 'bed': 11090,
 'comfortable': 18553,
 'woke': 80136,
 'stiff': 68860,
 'neck': 48790,
 'high': 36036,
 'pillows': 54643,
 'soundproof': 67119,
 'like': 42920,
 'heard': 35439,
 'music': 48313,
 'night': 49383,
 'morning': 47723,
 'loud': 43892,
 'bangs': 9939,
 'doors': 24555,
 'opening': 51490,
 'closing': 17921,
 'hear': 35436,
 'people': 53896,
 'talking': 70917,
 'hallway': 34815,
 'maybe': 45647,
 'noisy': 49763,
 'neighbors': 48969,
 'aveda': 9092,
 'bath': 10462,
 'products': 57041,
 'goldfish': 33298,
 'to

In [124]:
# Create a TDM

In [125]:
tdm = bow_transformer.transform(ta.X)

In [126]:
tdm.shape

(20491, 81408)

In [127]:
# tdm will act as our X  - using tdm we will build the model

#### Sampling stage:--

In [128]:
from sklearn.model_selection import train_test_split

In [129]:
train_X  , test_X , train_Y  , test_Y = train_test_split(tdm , ta.Y , test_size = .2)

#### model building stage:--

In [130]:
# NAIVE BAYES

In [131]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(train_X , train_Y)

MultinomialNB()

In [132]:
pred = nb.predict(test_X)

In [133]:
from sklearn.metrics import confusion_matrix , classification_report

In [134]:
tab = confusion_matrix(test_Y , pred)
tab

array([[ 749,  358],
       [ 118, 2874]], dtype=int64)

In [136]:
tab_cf = pd.DataFrame(tab)
tab_cf.columns = [1 ,2]
tab_cf.index = [ 1 ,2]
tab_cf

1     2
1  749   358
2  118  2874

In [137]:
print(classification_report(test_Y , pred))

              precision    recall  f1-score   support

           1       0.86      0.68      0.76      1107
           2       0.89      0.96      0.92      2992

    accuracy                           0.88      4099
   macro avg       0.88      0.82      0.84      4099
weighted avg       0.88      0.88      0.88      4099



In [94]:
# DECISION TREE

In [138]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight='balanced')
dt.fit(train_X , train_Y)

DecisionTreeClassifier(class_weight='balanced')

In [139]:
pred_test_rf = dt.predict(test_X)

In [140]:
tab = confusion_matrix(test_Y , pred_test_rf)
tab

array([[ 677,  430],
       [ 497, 2495]], dtype=int64)

In [141]:
tab_cf = pd.DataFrame(tab)
tab_cf.columns = [1 ,2]
tab_cf.index = [ 1 ,2]
tab_cf

1     2
1  677   430
2  497  2495

In [142]:
print(classification_report(test_Y , pred_test_rf))

              precision    recall  f1-score   support

           1       0.58      0.61      0.59      1107
           2       0.85      0.83      0.84      2992

    accuracy                           0.77      4099
   macro avg       0.71      0.72      0.72      4099
weighted avg       0.78      0.77      0.78      4099



In [143]:
# LOGISTIC Regression :--

In [144]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(train_X , train_Y);
lr

C:\Users\HARSH\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [145]:
pred_test = lr.predict(test_X)
pred_test

array([2, 2, 2, ..., 2, 1, 2], dtype=int64)

In [146]:
from sklearn.metrics import *

In [104]:
tab = confusion_matrix(test_Y , pred_test_rf)
tab

array([[ 355,   73,  196],
       [ 101,   74,  268],
       [ 218,  192, 2622]], dtype=int64)

In [147]:
tab_cf = pd.DataFrame(tab)
tab_cf.columns = [1 ,2]
tab_cf.index = [ 1 ,2]
tab_cf

1     2
1  677   430
2  497  2495

In [148]:
print(classification_report(test_Y , pred_test_rf))

              precision    recall  f1-score   support

           1       0.58      0.61      0.59      1107
           2       0.85      0.83      0.84      2992

    accuracy                           0.77      4099
   macro avg       0.71      0.72      0.72      4099
weighted avg       0.78      0.77      0.78      4099



In [107]:
# RANDOM FOREST

In [162]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=50 , class_weight='balanced', criterion='gini' , max_depth=7,min_samples_split= 29)
rfc.fit(train_X , train_Y)
pred_rfc = rfc.predict(test_X)
tab_rfc = confusion_matrix(test_Y , pred_rfc)
tab_rfc

array([[ 828,  279],
       [ 450, 2542]], dtype=int64)

In [156]:
#from sklearn.model_selection import GridSearchCV

In [157]:
# search_dict = {'criterion':['gini','entropy'] , 
#                'max_depth':range(5,10) , 
#                 'min_samples_split':range(25,30)}

In [158]:
# grid = GridSearchCV(dt , param_grid=search_dict)

In [160]:
# grid.fit(train_X , train_Y)

GridSearchCV(estimator=DecisionTreeClassifier(class_weight='balanced'),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(5, 10),
                         'min_samples_split': range(25, 30)})

In [161]:
# grid.best_params_ 

{'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 29}

In [ ]:
# now we use above hyperparameter values to build Decision Tree.

In [151]:
tab_cf = pd.DataFrame(tab_rfc)
tab_cf.columns = [1 ,2]
tab_cf.index = [ 1 ,2]
tab_cf

1     2
1  461   646
2   26  2966

In [152]:
print(classification_report(test_Y , pred_rfc))

              precision    recall  f1-score   support

           1       0.95      0.42      0.58      1107
           2       0.82      0.99      0.90      2992

    accuracy                           0.84      4099
   macro avg       0.88      0.70      0.74      4099
weighted avg       0.86      0.84      0.81      4099



In [153]:
# SVM

In [154]:
from sklearn.svm import SVC
svc_al = SVC()
svc_al.fit(train_X , train_Y)

SVC()

In [163]:
pred_svc= svc_al.predict(test_X)

In [164]:
from sklearn.metrics import *

In [165]:
tab = confusion_matrix(test_Y , pred)
tab

array([[ 749,  358],
       [ 118, 2874]], dtype=int64)

In [166]:
tab_cf = pd.DataFrame(tab)
tab_cf.columns = [1 ,2]
tab_cf.index = [ 1 ,2]
tab_cf

1     2
1  749   358
2  118  2874

In [167]:
print(classification_report(test_Y , pred))

              precision    recall  f1-score   support

           1       0.86      0.68      0.76      1107
           2       0.89      0.96      0.92      2992

    accuracy                           0.88      4099
   macro avg       0.88      0.82      0.84      4099
weighted avg       0.88      0.88      0.88      4099

